# Generated by Django 3.1.3 on 2020-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('companies', models.ManyToManyField(to='companies.Company')),
            ],
        ),
    ]
