# Generated by Django 3.1.3 on 2020-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201114_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
