# Generated by Django 3.1.3 on 2020-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20201114_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
